tree = {
    "id": 94271844554144,
    "type": "root",
    "orientation": "horizontal",
    "scratchpad_state": "none",
    "percent": 1.0,
    "urgent": False,
    "focused": False,
    "layout": "splith",
    "workspace_layout": "default",
    "last_split_layout": "splith",
    "border": "normal",
    "current_border_width": -1,
    "rect": {"x": 0, "y": 0, "width": 1920, "height": 1080},
    "deco_rect": {"x": 0, "y": 0, "width": 0, "height": 0},
    "window_rect": {"x": 0, "y": 0, "width": 0, "height": 0},
    "geometry": {"x": 0, "y": 0, "width": 0, "height": 0},
    "name": "root",
    "window": None,
    "nodes": [
        {
            "id": 94271844556896,
            "type": "output",
            "orientation": "none",
            "scratchpad_state": "none",
            "percent": 0.5,
            "urgent": False,
            "focused": False,
            "layout": "output",
            "workspace_layout": "default",
            "last_split_layout": "splith",
            "border": "normal",
            "current_border_width": -1,
            "rect": {"x": 0, "y": 0, "width": 1920, "height": 1080},
            "deco_rect": {"x": 0, "y": 0, "width": 0, "height": 0},
            "window_rect": {"x": 0, "y": 0, "width": 0, "height": 0},
            "geometry": {"x": 0, "y": 0, "width": 0, "height": 0},
            "name": "__i3",
            "window": None,
            "nodes": [
                {
                    "id": 94271844557392,
                    "type": "con",
                    "orientation": "horizontal",
                    "scratchpad_state": "none",
                    "percent": 1.0,
                    "urgent": False,
                    "focused": False,
                    "output": "__i3",
                    "layout": "splith",
                    "workspace_layout": "default",
                    "last_split_layout": "splith",
                    "border": "normal",
                    "current_border_width": -1,
                    "rect": {"x": 0, "y": 0, "width": 0, "height": 0},
                    "deco_rect": {"x": 0, "y": 0, "width": 0, "height": 0},
                    "window_rect": {"x": 0, "y": 0, "width": 0, "height": 0},
                    "geometry": {"x": 0, "y": 0, "width": 0, "height": 0},
                    "name": "content",
                    "window": None,
                    "nodes": [
                        {
                            "id": 94271844557888,
                            "type": "workspace",
                            "orientation": "none",
                            "scratchpad_state": "none",
                            "percent": 1.0,
                            "urgent": False,
                            "focused": False,
                            "output": "__i3",
                            "layout": "splith",
                            "workspace_layout": "default",
                            "last_split_layout": "splith",
                            "border": "normal",
                            "current_border_width": -1,
                            "rect": {"x": 0, "y": 0, "width": 0, "height": 0},
                            "deco_rect": {"x": 0, "y": 0, "width": 0, "height": 0},
                            "window_rect": {"x": 0, "y": 0, "width": 0, "height": 0},
                            "geometry": {"x": 0, "y": 0, "width": 0, "height": 0},
                            "name": "__i3_scratch",
                            "num": -1,
                            "window": None,
                            "nodes": [],
                            "floating_nodes": [
                                {
                                    "id": 94271844692688,
                                    "type": "floating_con",
                                    "orientation": "horizontal",
                                    "scratchpad_state": "changed",
                                    "percent": None,
                                    "urgent": False,
                                    "focused": False,
                                    "output": "__i3",
                                    "layout": "splith",
                                    "workspace_layout": "default",
                                    "last_split_layout": "splith",
                                    "border": "normal",
                                    "current_border_width": -1,
                                    "rect": {
                                        "x": 589,
                                        "y": 333,
                                        "width": 743,
                                        "height": 440,
                                    },
                                    "deco_rect": {
                                        "x": 0,
                                        "y": 0,
                                        "width": 0,
                                        "height": 0,
                                    },
                                    "window_rect": {
                                        "x": 0,
                                        "y": 0,
                                        "width": 0,
                                        "height": 0,
                                    },
                                    "geometry": {
                                        "x": 0,
                                        "y": 0,
                                        "width": 0,
                                        "height": 0,
                                    },
                                    "name": None,
                                    "window": None,
                                    "nodes": [
                                        {
                                            "id": 94271844689472,
                                            "type": "con",
                                            "orientation": "none",
                                            "scratchpad_state": "none",
                                            "percent": 1.0,
                                            "urgent": False,
                                            "marks": ["my_mark"],
                                            "focused": False,
                                            "output": "__i3",
                                            "layout": "splith",
                                            "workspace_layout": "default",
                                            "last_split_layout": "splith",
                                            "border": "none",
                                            "current_border_width": 0,
                                            "rect": {
                                                "x": 589,
                                                "y": 333,
                                                "width": 743,
                                                "height": 440,
                                            },
                                            "deco_rect": {
                                                "x": 0,
                                                "y": 0,
                                                "width": 0,
                                                "height": 0,
                                            },
                                            "window_rect": {
                                                "x": 0,
                                                "y": 0,
                                                "width": 743,
                                                "height": 440,
                                            },
                                            "geometry": {
                                                "x": 0,
                                                "y": 0,
                                                "width": 743,
                                                "height": 440,
                                            },
                                            "name": "notes",
                                            "window": 39845891,
                                            "window_properties": {
                                                "class": "Termite",
                                                "instance": "test-termite",
                                                "title": "notes",
                                                "transient_for": None,
                                            },
                                            "nodes": [],
                                            "floating_nodes": [],
                                            "focus": [],
                                            "fullscreen_mode": 0,
                                            "sticky": False,
                                            "floating": "user_on",
                                            "swallows": [],
                                        }
                                    ],
                                    "floating_nodes": [],
                                    "focus": [94271844689472],
                                    "fullscreen_mode": 0,
                                    "sticky": False,
                                    "floating": "auto_off",
                                    "swallows": [],
                                }
                            ],
                            "focus": [94271844692688],
                            "fullscreen_mode": 1,
                            "sticky": False,
                            "floating": "auto_off",
                            "swallows": [],
                        }
                    ],
                    "floating_nodes": [],
                    "focus": [94271844557888],
                    "fullscreen_mode": 0,
                    "sticky": False,
                    "floating": "auto_off",
                    "swallows": [],
                }
            ],
            "floating_nodes": [],
            "focus": [94271844557392],
            "fullscreen_mode": 0,
            "sticky": False,
            "floating": "auto_off",
            "swallows": [],
        },
        {
            "id": 94271844625344,
            "type": "output",
            "orientation": "none",
            "scratchpad_state": "none",
            "percent": 0.5,
            "urgent": False,
            "focused": False,
            "layout": "output",
            "workspace_layout": "default",
            "last_split_layout": "splith",
            "border": "normal",
            "current_border_width": -1,
            "rect": {"x": 0, "y": 0, "width": 1920, "height": 1080},
            "deco_rect": {"x": 0, "y": 0, "width": 0, "height": 0},
            "window_rect": {"x": 0, "y": 0, "width": 0, "height": 0},
            "geometry": {"x": 0, "y": 0, "width": 0, "height": 0},
            "name": "eDP1",
            "window": None,
            "nodes": [
                {
                    "id": 94271844651552,
                    "type": "con",
                    "orientation": "horizontal",
                    "scratchpad_state": "none",
                    "percent": None,
                    "urgent": False,
                    "focused": False,
                    "output": "eDP1",
                    "layout": "splith",
                    "workspace_layout": "default",
                    "last_split_layout": "splith",
                    "border": "normal",
                    "current_border_width": -1,
                    "rect": {"x": 0, "y": 27, "width": 1920, "height": 1053},
                    "deco_rect": {"x": 0, "y": 0, "width": 0, "height": 0},
                    "window_rect": {"x": 0, "y": 0, "width": 0, "height": 0},
                    "geometry": {"x": 0, "y": 0, "width": 0, "height": 0},
                    "name": "content",
                    "window": None,
                    "nodes": [
                        {
                            "id": 94271844693152,
                            "type": "workspace",
                            "orientation": "horizontal",
                            "scratchpad_state": "none",
                            "percent": None,
                            "urgent": False,
                            "focused": False,
                            "output": "eDP1",
                            "layout": "splith",
                            "workspace_layout": "default",
                            "last_split_layout": "splith",
                            "border": "normal",
                            "current_border_width": -1,
                            "rect": {"x": 0, "y": 27, "width": 1920, "height": 1053},
                            "deco_rect": {"x": 0, "y": 0, "width": 0, "height": 0},
                            "window_rect": {"x": 0, "y": 0, "width": 0, "height": 0},
                            "geometry": {"x": 0, "y": 0, "width": 0, "height": 0},
                            "name": "workspace_2",
                            "num": -1,
                            "window": None,
                            "nodes": [
                                {
                                    "id": 94271844692688,
                                    "type": "con",
                                    "orientation": "none",
                                    "scratchpad_state": "none",
                                    "percent": 1.0,
                                    "urgent": False,
                                    "focused": False,
                                    "output": "eDP1",
                                    "layout": "splith",
                                    "workspace_layout": "default",
                                    "last_split_layout": "splith",
                                    "border": "none",
                                    "current_border_width": 0,
                                    "rect": {
                                        "x": 0,
                                        "y": 27,
                                        "width": 1920,
                                        "height": 1053,
                                    },
                                    "deco_rect": {
                                        "x": 0,
                                        "y": 0,
                                        "width": 0,
                                        "height": 0,
                                    },
                                    "window_rect": {
                                        "x": 0,
                                        "y": 0,
                                        "width": 1920,
                                        "height": 1053,
                                    },
                                    "geometry": {
                                        "x": 0,
                                        "y": 0,
                                        "width": 1920,
                                        "height": 1053,
                                    },
                                    "name": "Home",
                                    "window": 46153256,
                                    "window_properties": {
                                        "class": "Nemo",
                                        "instance": "nemo",
                                        "title": "Home",
                                        "transient_for": None,
                                    },
                                    "nodes": [],
                                    "floating_nodes": [],
                                    "focus": [],
                                    "fullscreen_mode": 0,
                                    "sticky": False,
                                    "floating": "auto_off",
                                    "swallows": [],
                                }
                            ],
                            "floating_nodes": [],
                            "focus": [94271844826512, 94271844692688],
                            "fullscreen_mode": 1,
                            "sticky": False,
                            "floating": "auto_off",
                            "swallows": [],
                        },
                        {
                            "id": 94271844615376,
                            "type": "workspace",
                            "orientation": "horizontal",
                            "scratchpad_state": "none",
                            "percent": 1.0,
                            "urgent": False,
                            "focused": False,
                            "output": "eDP1",
                            "layout": "splith",
                            "workspace_layout": "default",
                            "last_split_layout": "splith",
                            "border": "normal",
                            "current_border_width": -1,
                            "rect": {"x": 0, "y": 27, "width": 1920, "height": 1053},
                            "deco_rect": {"x": 0, "y": 0, "width": 0, "height": 0},
                            "window_rect": {"x": 0, "y": 0, "width": 0, "height": 0},
                            "geometry": {"x": 0, "y": 0, "width": 0, "height": 0},
                            "name": "workspace_1",
                            "num": -1,
                            "window": None,
                            "nodes": [
                                {
                                    "id": 94271844619504,
                                    "type": "con",
                                    "orientation": "none",
                                    "scratchpad_state": "none",
                                    "percent": 0.5,
                                    "urgent": False,
                                    "marks": ["my_qb_mark"],
                                    "focused": True,
                                    "output": "eDP1",
                                    "layout": "splith",
                                    "workspace_layout": "default",
                                    "last_split_layout": "splith",
                                    "border": "none",
                                    "current_border_width": 0,
                                    "rect": {
                                        "x": 0,
                                        "y": 27,
                                        "width": 960,
                                        "height": 1053,
                                    },
                                    "deco_rect": {
                                        "x": 0,
                                        "y": 0,
                                        "width": 0,
                                        "height": 0,
                                    },
                                    "window_rect": {
                                        "x": 0,
                                        "y": 0,
                                        "width": 960,
                                        "height": 1053,
                                    },
                                    "geometry": {
                                        "x": 0,
                                        "y": 27,
                                        "width": 1920,
                                        "height": 1053,
                                    },
                                    "name": "i3 - improved tiling wm - qutebrowser",
                                    "window": 33554459,
                                    "window_properties": {
                                        "class": "qutebrowser",
                                        "instance": "test-qutebrowser",
                                        "title": "i3 - improved tiling wm - qutebrowser",
                                        "transient_for": None,
                                    },
                                    "nodes": [],
                                    "floating_nodes": [],
                                    "focus": [],
                                    "fullscreen_mode": 1,
                                    "sticky": False,
                                    "floating": "auto_off",
                                    "swallows": [],
                                }
                            ],
                            "floating_nodes": [
                                {
                                    "id": 94271844826512,
                                    "type": "floating_con",
                                    "orientation": "horizontal",
                                    "scratchpad_state": "changed",
                                    "percent": None,
                                    "urgent": False,
                                    "focused": False,
                                    "output": "eDP1",
                                    "layout": "splith",
                                    "workspace_layout": "default",
                                    "last_split_layout": "splith",
                                    "border": "normal",
                                    "current_border_width": -1,
                                    "rect": {
                                        "x": 589,
                                        "y": 333,
                                        "width": 743,
                                        "height": 440,
                                    },
                                    "deco_rect": {
                                        "x": 0,
                                        "y": 0,
                                        "width": 0,
                                        "height": 0,
                                    },
                                    "window_rect": {
                                        "x": 0,
                                        "y": 0,
                                        "width": 0,
                                        "height": 0,
                                    },
                                    "geometry": {
                                        "x": 0,
                                        "y": 0,
                                        "width": 0,
                                        "height": 0,
                                    },
                                    "name": None,
                                    "window": None,
                                    "nodes": [
                                        {
                                            "id": 94271844845984,
                                            "type": "con",
                                            "orientation": "none",
                                            "scratchpad_state": "none",
                                            "percent": 1.0,
                                            "urgent": False,
                                            "focused": False,
                                            "output": "eDP1",
                                            "layout": "splith",
                                            "workspace_layout": "default",
                                            "last_split_layout": "splith",
                                            "border": "none",
                                            "current_border_width": 0,
                                            "rect": {
                                                "x": 589,
                                                "y": 333,
                                                "width": 743,
                                                "height": 440,
                                            },
                                            "deco_rect": {
                                                "x": 0,
                                                "y": 0,
                                                "width": 0,
                                                "height": 0,
                                            },
                                            "window_rect": {
                                                "x": 0,
                                                "y": 0,
                                                "width": 743,
                                                "height": 440,
                                            },
                                            "geometry": {
                                                "x": 0,
                                                "y": 0,
                                                "width": 743,
                                                "height": 440,
                                            },
                                            "name": "htop",
                                            "window": 50331651,
                                            "window_properties": {
                                                "class": "Termite",
                                                "instance": "termite",
                                                "title": "htop",
                                                "transient_for": None,
                                            },
                                            "nodes": [],
                                            "floating_nodes": [],
                                            "focus": [],
                                            "fullscreen_mode": 0,
                                            "sticky": False,
                                            "floating": "user_on",
                                            "swallows": [],
                                        }
                                    ],
                                    "floating_nodes": [],
                                    "focus": [94271844845984],
                                    "fullscreen_mode": 0,
                                    "sticky": False,
                                    "floating": "auto_off",
                                    "swallows": [],
                                }
                            ],
                            "focus": [94271844644304, 94271844619504],
                            "fullscreen_mode": 1,
                            "sticky": False,
                            "floating": "auto_off",
                            "swallows": [],
                        },
                    ],
                    "floating_nodes": [],
                    "focus": [94271844615376],
                    "fullscreen_mode": 0,
                    "sticky": False,
                    "floating": "auto_off",
                    "swallows": [],
                },
                {
                    "id": 94271844673008,
                    "type": "dockarea",
                    "orientation": "none",
                    "scratchpad_state": "none",
                    "percent": None,
                    "urgent": False,
                    "focused": False,
                    "output": "eDP1",
                    "layout": "dockarea",
                    "workspace_layout": "default",
                    "last_split_layout": "splith",
                    "border": "normal",
                    "current_border_width": -1,
                    "rect": {"x": 0, "y": 1080, "width": 1920, "height": 0},
                    "deco_rect": {"x": 0, "y": 0, "width": 0, "height": 0},
                    "window_rect": {"x": 0, "y": 0, "width": 0, "height": 0},
                    "geometry": {"x": 0, "y": 0, "width": 0, "height": 0},
                    "name": "bottomdock",
                    "window": None,
                    "nodes": [],
                    "floating_nodes": [],
                    "focus": [],
                    "fullscreen_mode": 0,
                    "sticky": False,
                    "floating": "auto_off",
                    "swallows": [{"dock": 3, "insert_where": 2}],
                },
            ],
            "floating_nodes": [],
            "focus": [94271844651552, 94271844651088, 94271844673008],
            "fullscreen_mode": 0,
            "sticky": False,
            "floating": "auto_off",
            "swallows": [],
        },
    ],
    "floating_nodes": [],
    "focus": [94271844625344, 94271844556896],
    "fullscreen_mode": 0,
    "sticky": False,
    "floating": "auto_off",
    "swallows": [],
}
